# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/build/javascript" # Location of package manifests
    open-pull-requests-limit: 3
    schedule:
      interval: "daily"
    reviewers:
      - "gabek"

  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: "daily"
    reviewers:
      - "gabek"
    ignore:
      # Ignore patch revisions of the aws sdk
      - dependency-name: "aws-sdk-go"
        update-types: ["version-update:semver-patch"]
