publicHLSPath: webroot/hls
privateHLSPath: hls
ffmpegPath: /usr/bin/ffmpeg
webServerPort: 8080

videoSettings:
  chunkLengthInSeconds: 4
  streamingKey: abc123
  offlineContent: static/offline.m4v # Is displayed when a stream ends

  streamQualities:
    # Pass through the exact video and audio that you're streaming.
    - full:
      videoPassthrough: true
      audioPassthrough: true

    # Transcode the video to a lower bitrate and resize
    # - low:
    # bitrate: 700
    # scaledWidth: 600
    # audioPassthrough: true
    # encoderPreset: superfast

files:
  maxNumberInPlaylist: 30

ipfs:
  enabled: false
  gateway: https://ipfs.io

s3:
  enabled: false
  endpoint: https://s3.us-west-2.amazonaws.com
  accessKey: ABC12342069
  secret: lolomgqwtf49583949
  region: us-west-2
  bucket: myvideo
