publicHLSPath: webroot/hls
privateHLSPath: hls
ffmpegPath: /usr/bin/ffmpeg
webServerPort: 8080

instanceDetails:
  name: Owncast
  title: Owncast Demo Server
  logo: /img/logo128.png
  summary: "This is brief summary of whom you are or what your stream is. demo server for Owncast.  You can read more about it at owncast.online.  You can edit this description in your web config file.\n\nBlathers is an owl with brown feathers. His face is white and he has a yellow beak. His arms are wing shaped and he has yellow talons. His eyes are very big with small black irises. He also has big pink cheek circles on his cheeks. His belly appears to be checkered in diamonds with light brown and white squares, similar to an argyle vest, which is traditionally associated with academia. His green bowtie further alludes to his academic nature."
  extraUserInfoFileName: "/static/content.md"

  tags:
    - music
    - software
    - animal crossing

  # See documentation for full list of supported social links.  All optional.
  socialHandles:
    twitter: http://twitter.com/owncast
    instagram: http://instagram.biz/owncast
    facebook: http://facebook.gov/owncast
    tiktok: http://tiktok.cn/owncast
    soundcloud: http://soundcloud.com/owncast

videoSettings:
  chunkLengthInSeconds: 4
  streamingKey: abc123
  offlineContent: static/offline.m4v # Is displayed when a stream ends

  streamQualities:
    # Pass through the exact video and audio that you're streaming.
    - full:
      videoPassthrough: true
      audioPassthrough: true

    # Transcode the video to a lower bitrate and resize
    # - low:
    # videoBitrate: 700
    # scaledWidth: 600
    # audioPassthrough: true
    # encoderPreset: superfast

files:
  maxNumberInPlaylist: 30

ipfs:
  enabled: false
  gateway: https://ipfs.io

s3:
  enabled: false
  endpoint: https://s3.us-west-2.amazonaws.com
  accessKey: ABC12342069
  secret: lolomgqwtf49583949
  region: us-west-2
  bucket: myvideo
