publicHLSPath: webroot/hls
privateHLSPath: hls
ffmpegPath: /usr/local/bin/ffmpeg
webServerPort: 8080

videoSettings:
  chunkLengthInSeconds: 4
  streamingKey: abc123

  streamQualities:
    - bitrate: 6000k

files:
  maxNumberInPlaylist: 30
  maxNumberOnDisk: 60

ipfs:
  enabled: false
  gateway: https://ipfs.io

s3:
  enabled: false
  accessKey: ABC12342069
  secret: lolomgqwtf49583949
  region: us-west-2
  bucket: myvideo