name: Automated API tests

on:
  push:
    paths-ignore:
      - 'webroot/**'
  pull_request:
    paths-ignore:
      - 'webroot/**'
      
jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          stable: 'false'
          go-version: '1.17.2'
      - name: Run API tests
        run: cd test/automated/api && ./run.sh

  