name: Automated browser tests
on: [push, pull_request]
jobs:
  browser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          stable: 'false'
          go-version: '1.17.2'

      - name: Run browser tests
        run: cd test/automated/browser && ./run.sh

      - uses: actions/upload-artifact@v2
        with:
          name: screenshots-${{ github.run_id }}
          path: test/automated/browser/screenshots/*.png
