name: javascript-packages
on:
  push:
    paths:
      - build/javascript/**

jobs:
  run:
    name: npm run build
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v2

        - name: Install dependencies
          run: cd build/javascript && npm run build

        - name: Commit changes
          uses: EndBug/add-and-commit@v5
          with:
            author_name: Owncast
            author_email: owncast@owncast.online
            message: "Commit updated Javascript packages"
            add: "build/javascript"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
