name: Take nightly screenshots

on:
  schedule:
    - cron: '0 4 * * *'

env:
  BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
  BROWSERSTACK_PASSWORD: ${{ secrets.BROWSERSTACK_PASSWORD }}
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
  TEST_URL: http://localhost:8080

jobs:
  Screenshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.8'

      - name: Automate screenshots
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 4
          command: cd test/automated/screenshots && ./run.sh

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Owncast
          author_email: owncast@owncast.online
          message: 'Commit screenshots'
          add: '*.png'
          pull: '--rebase --autostash'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Dispatch event to web site
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.BUNDLE_STORYBOOK_OWNCAST_ONLINE }}
          repository: owncast/owncast.github.io
          event-type: bundle-components-library
